# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0002_shorturl_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='shortCode',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
